/* AUTO-GENERATED by tools/gen_assets.py from the assets/ directory -- DO NOT EDIT */
#ifndef INFINITE_BEST_ASSETS_H
#define INFINITE_BEST_ASSETS_H

#include <stdint.h>

/* ---- tile index layout (shared 256-tile space at 0x8000) ---- */
#define TILE_FONT_BASE 0
#define TILE_UI_BASE 64
#define TILE_MT_BASE 80
#define TILE_SPR_BASE 160
#define TILE_FADE_BASE 192
#define NUM_FONT_TILES 64
#define NUM_UI_TILES 16
#define NUM_SPR_TILES 32
#define NUM_FADE_TILES 8
#define TILE_BLANK 0                           /* space: all index 0 */
#define TILE_SOLID3 (TILE_FADE_BASE + NUM_FADE_TILES - 1) /* all index 3 */
#define FONT_TILE(ch) ((uint8_t)((ch) - 32 + TILE_FONT_BASE)) /* ASCII 32..95 */
#define MT_TILE(m, corner) ((uint8_t)(TILE_MT_BASE + ((m) << 2) + (corner))) /* corner 0=TL 1=TR 2=BL 3=BR */

/* UI tiles: absolute tile indices.  The box edges are symmetric, so
   UI_BOX_B == UI_BOX_T and UI_BOX_R == UI_BOX_L; box interior = TILE_BLANK */
enum {
    UI_BOLT = TILE_UI_BASE + 0,
    UI_STEP = TILE_UI_BASE + 1,
    UI_STAR = TILE_UI_BASE + 2,
    UI_CHIP = TILE_UI_BASE + 3,
    UI_FLAG = TILE_UI_BASE + 4,
    UI_BOX_TL = TILE_UI_BASE + 5,
    UI_BOX_T = TILE_UI_BASE + 6,
    UI_BOX_B = TILE_UI_BASE + 6,
    UI_BOX_TR = TILE_UI_BASE + 7,
    UI_BOX_L = TILE_UI_BASE + 8,
    UI_BOX_R = TILE_UI_BASE + 8,
    UI_BOX_BL = TILE_UI_BASE + 9,
    UI_BOX_BR = TILE_UI_BASE + 10,
    UI_BAR_FULL = TILE_UI_BASE + 11,
    UI_BAR_HALF = TILE_UI_BASE + 12,
    UI_CHIP_EMPTY = TILE_UI_BASE + 13,
    UI_INFINITY_L = TILE_UI_BASE + 14,
    UI_INFINITY_R = TILE_UI_BASE + 15
};

/* metatile ids; tile of metatile m corner c = TILE_MT_BASE + m*4 + c */
enum {
    MT_FLOOR = 0,
    MT_WALL,
    MT_WALL2,
    MT_EXIT_LOCKED,
    MT_EXIT_OPEN,
    MT_EXIT_OPEN2,
    MT_CHIP,
    MT_STOP,
    MT_ARROW_U,
    MT_ARROW_R,
    MT_ARROW_D,
    MT_ARROW_L,
    MT_SWITCH_0,
    MT_SWITCH_1,
    MT_GATE_A_CLOSED,
    MT_GATE_A_OPEN,
    MT_GATE_B_CLOSED,
    MT_GATE_B_OPEN,
    MT_PORTAL,
    MT_PIT,
    NUM_MT
};

/* sprite tiles: absolute indices; 16x16 player frames are TL,TR,BL,BR.
   SPR_HINT_UP/RIGHT: flip for down/left.  SPR_RING_B is the top-left
   quarter of a 16x16 ring: draw 4 with X/Y flips */
enum {
    SPR_PLAYER_IDLE = TILE_SPR_BASE + 0,
    SPR_PLAYER_BLINK = TILE_SPR_BASE + 4,
    SPR_PLAYER_SQUASH = TILE_SPR_BASE + 8,
    SPR_PLAYER_DEAD = TILE_SPR_BASE + 12,
    SPR_SPARK_BIG = TILE_SPR_BASE + 16,
    SPR_SPARK_SMALL = TILE_SPR_BASE + 17,
    SPR_PIXEL = TILE_SPR_BASE + 18,
    SPR_TRAIL = TILE_SPR_BASE + 19,
    SPR_HINT_UP = TILE_SPR_BASE + 20,
    SPR_HINT_RIGHT = TILE_SPR_BASE + 21,
    SPR_CURSOR = TILE_SPR_BASE + 22,
    SPR_STAR = TILE_SPR_BASE + 23,
    SPR_RING_A = TILE_SPR_BASE + 24,
    SPR_RING_B = TILE_SPR_BASE + 25
};
#define SPR_FIRST_FREE (TILE_SPR_BASE + 26)  /* unused (blank) slots up to 191 */

extern const uint8_t font_tiles[64*16];
extern const uint8_t ui_tiles[16*16];
extern const uint8_t mt_tiles[NUM_MT*4*16];
extern const uint8_t spr_tiles[32*16];
extern const uint8_t fade_tiles[NUM_FADE_TILES*16];

/* ---- title logo (tiles load at TILE_MT_BASE; map holds ABSOLUTE indices) ---- */
#define LOGO_W 20
#define LOGO_H 7
#define LOGO_NTILES 79
extern const uint8_t logo_tiles[LOGO_NTILES*16];
extern const uint8_t logo_map[LOGO_W*LOGO_H];

/* ---- CGB palettes ---- */
/* BG palette numbers */
#define PAL_UI 0
#define PAL_WALL 1
#define PAL_CHIP 2
#define PAL_GATE_A 3
#define PAL_AMBER 4
#define PAL_STOP 5
#define PAL_PORTAL 6
#define PAL_PIT 7
#define PAL_EXIT PAL_UI           /* exit port (cyan) */
#define PAL_ARROW PAL_AMBER       /* conveyors (yellow) */
#define PAL_GATE_B PAL_AMBER      /* gate B (amber) */
#define PAL_SWITCH PAL_CHIP       /* toggle switch (green) */
#define PAL_HUD_ACCENT PAL_AMBER  /* HUD icons: bolt/step/star/flag/bar/infinity */
#define PAL_HUD_CHIP PAL_CHIP     /* HUD chip counter icon */
#define PAL_LOGO PAL_UI           /* logo "INFINITE" */
#define PAL_LOGO2 PAL_GATE_A      /* logo "BEST" */
#define PAL_LOGO3 PAL_AMBER       /* logo infinity divider */
/* sprite palette numbers */
#define SPAL_PLAYER 0
#define SPAL_SPARK 1
#define SPAL_HINT 2
#define SPAL_STAR 3
#define SPAL_TRAIL 4
#define SPAL_DEAD 5
#define SPAL_CURSOR 6
#define SPAL_WHITE 7
/* DMG palettes: inverted so index 0 = black, 3 = white */
#define DMG_BGP 0x1B
#define DMG_OBP0 0x1B
#define DMG_OBP1 0x4B
extern const uint8_t mt_cgb_pal[NUM_MT];     /* BG palette per metatile */
extern const uint8_t logo_cgb_attr[LOGO_W*LOGO_H]; /* BG palette per logo cell */
extern const uint16_t bg_cgb_pal[8*4];       /* RGB555: r | g<<5 | b<<10 */
extern const uint16_t spr_cgb_pal[8*4];

#endif
