/* music_data.h - GENERATED by tools/gen_music.py, do not edit. */
#ifndef MUSIC_DATA_H
#define MUSIC_DATA_H

#include <stdint.h>

/* pattern stream byte codes */
#define SND_CMD_LEN   0x80 /* 0x80..0xBF: len=(b&0x3F)+1 rows */
#define SND_CMD_REST  0xC0
#define SND_CMD_HOLD  0xC1
#define SND_CMD_INST  0xC2 /* + instrument */
#define SND_CMD_ARP   0xC3 /* + xy */
#define SND_CMD_GLIDE 0xC4
#define SND_CMD_END   0xFF
#define SND_ORD_JUMP  0xFF /* + byte offset into order list */
#define SND_ORD_END   0xFE
#define SND_NUM_NOTES 96
#define SND_NUM_INSTS 16
#define SND_NUM_DRUMS 11
#define SND_NUM_WAVES 3
#define SND_NUM_PATTERNS 50

/* Instrument (8 bytes, ROM).
 *   pulse: env = NRx2 envelope, duty/alt = duty 0..3, rate = frames between
 *          duty toggles (0 = no duty macro)
 *   wave : env = start output level code 1..3 (100/50/25%), duty = wavetable
 *          index, rate = frames per level-decay step (0 = sustain)
 *   all  : vshift = vibrato depth (period >> vshift, 0 = off), vrate = LFO
 *          phase step per frame (256 = full cycle), vdelay = frames before
 *          vibrato, cut = frames until auto note-off (0 = none) */
typedef struct {
    uint8_t env, duty, alt, rate, vshift, vrate, vdelay, cut;
} snd_inst_t;

/* Noise drum: NR42 envelope + up to 4 per-frame NR43 values. */
typedef struct {
    uint8_t env, len, seq[4];
} snd_drum_t;

typedef struct {
    uint8_t speed_a, speed_b;       /* frames per row, alternating (groove) */
    const uint8_t *ord[4];          /* order lists: (pattern, transpose)* */
} snd_song_t;

/* SFX stream: [reg(0x10..0x3F), value]* ... 0x40+n = end of frame, then n
 * idle frames ... 0x00 = end.  mask: bit0 pulse1, bit1 pulse2, bit2 wave,
 * bit3 noise. */
typedef struct {
    const uint8_t *data;
    uint8_t mask, prio;
} snd_sfx_t;

extern const uint16_t snd_freq[SND_NUM_NOTES];
extern const snd_inst_t snd_insts[SND_NUM_INSTS];
extern const snd_drum_t snd_drums[SND_NUM_DRUMS];
extern const uint8_t snd_waves[SND_NUM_WAVES][16];
extern const uint8_t * const snd_patterns[SND_NUM_PATTERNS];
extern const snd_song_t snd_songs[5];
extern const snd_sfx_t snd_sfx[17];
/* approximate lengths, for tests / tools */
extern const uint16_t snd_song_frames[5]; /* intro+loop body in frames */
extern const uint8_t snd_song_loops[5];   /* 1 = looping */
extern const uint8_t snd_sfx_frames[17];   /* sfx duration in frames */

#endif
